# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e86353c46afb909ccfb1c922e46a765d0f6175e8a83db82bb04bc6d6b157d07c63b2d38e2cabce57ffaf9afc2f3c742e8516a39d9a0bc21af141f4959b57849e

test:
  secret_key_base: 987e2ee2ae8b21063c1906f051c6698ce2630a5987a8845c17dee0ff515cf0dd5bdbc37a0093e82b17ca7336a75592f966e57786aabc72080a08b71657a8507d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
